name: hola mundo

on:
  push:
    branches:
      - main
      

jobs: 
  saludo:
    runs-on: ubuntu-latest
    steps: 
      - name: Muestra mensaje hola mundo
        run: echo "Hola mundo julian"
